Feature/nbuapi
voicehovski/CuBot pull request #3
Opened 2022-07-19 13:00 UTC by YevhenNesvit

2022-07-19 14:53 UTC, voicehovski requested changes

2022-07-19 14:53 UTC, voicehovski commented on src/main/java/goit3/cubot/nbuapi/Main.java
> +    private static final String DOLLAR = "USD";
Валюты лучше сделать посредством внешнего Enum

2022-07-19 14:53 UTC, voicehovski commented on src/main/java/goit3/cubot/nbuapi/NBU.java
> +    public String getNBUCurrenciesRate(String currency, int decimals) throws IOException {
Лучше пусть метод возвращает курс без привязки к количеству знаков. Отображение в соответствии с настройками пользователя - задача нашего бота, а задача модуля предоставить ПОЛНУЮ информацию об обменном курсе

2022-07-19 14:53 UTC, voicehovski commented on src/main/java/goit3/cubot/nbuapi/NBUCurrency.java
> +class NBUCurrency {
А что происходит здесь? Почему приватные плля без какого-либо досутпа?

2022-07-19 14:57 UTC, YevhenNesvit commented on src/main/java/goit3/cubot/nbuapi/NBUCurrency.java
> +class NBUCurrency {
Это объект, возвращаемый запросом, нет доступа только для не используемых полей

2022-07-19 14:58 UTC, YevhenNesvit commented on src/main/java/goit3/cubot/nbuapi/Main.java
> +    private static final String DOLLAR = "USD";
Это было сделано для теста просто

2022-07-19 15:14 UTC, voicehovski commented on src/main/java/goit3/cubot/nbuapi/Main.java
> +    private static final String DOLLAR = "USD";
Ok, я сделал enum - можно пользоваться

2022-07-19 15:19 UTC, YevhenNesvit commented on src/main/java/goit3/cubot/nbuapi/NBUCurrency.java
> +class NBUCurrency {
Добавил геттеры

2022-07-19 15:20 UTC, YevhenNesvit commented on src/main/java/goit3/cubot/nbuapi/NBU.java
> +    public String getNBUCurrenciesRate(String currency, int decimals) throws IOException {
Теперь просто возвращает курс

2022-07-19 15:55 UTC, YevhenNesvit commented on src/main/java/goit3/cubot/nbuapi/Main.java
> +    private static final String DOLLAR = "USD";
Заменил на enum, тест запускается из AppLauncher

2022-07-20 09:09 UTC, voicehovski requested changes
Убери папку .idea из коммита

2022-07-20 09:09 UTC, voicehovski commented on src/main/java/goit3/cubot/nbuapi/NBU.java
> +    public double getNBUCurrenciesRate(String currency) throws IOException {
Наследуй от Bank.  И вопрос что оно должно возвращать, оставляем пока открытым - BigDecimal универсальнее, но, возможно, избыточен

2022-07-20 09:09 UTC, voicehovski commented on src/main/java/goit3/cubot/nbuapi/NBUCurrency.java
> +class NBUCurrency {
А они нам нужны? Возможно можно обойтись без этой информации

2022-07-20 09:39 UTC, voicehovski approved these changes
Удалил папку .idea сам чтобы ускорить процесс. Надеюсь, ты не против ;)

2022-07-20 09:52 UTC, YevhenNesvit commented on src/main/java/goit3/cubot/nbuapi/NBUCurrency.java
> +class NBUCurrency {
Поля нужны, без них объект ответа не создать, геттеры не нужны, ну раз ты спросил я добавил))

2022-07-20 09:54 UTC, merged